services:
  tts-engine:
    env_file:
      - .env_vllm
    image: vllm/vllm-openai:v0.11.0
    ipc: host
    shm_size: 10.24gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    container_name: tts-engine
    command: --dtype bfloat16 --port 9090 --gpu-memory-utilization 0.9 --model Scicom-intl/Multilingual-TTS-1.7B-v0.1 --served-model-name scicom-ai-enterprise/TTS-1.7B-Stage2-english --max-model-len 4096 -O.cudagraph_mode=FULL_AND_PIECEWISE
    volumes:
      - "~/.cache/huggingface:/root/.cache/huggingface"
    ports:
      - "9090:9090"
    networks: ["tts-network"]

networks:
  tts-network:
    external: true