"""
Inputs for the normalizer ground truth (bench/normalizer_truth.py runs them through the live
LLM normalizer; bench/normalizer_agreement.py scores the rule normalizer against those outputs).

(id, lang, category, text). lang is the dominant language the numbers should be verbalized
in: en, ms, zh, ta, cs (Malay/English code-switch). Categories mirror the LLM prompt: int,
money, decimal, percent, phone, ic, date, time, ordinal, range, unit, email, url, id, year,
abbr, acro, plain (must come back unchanged), mixed (several categories in one sentence).

Keep ids stable: the truth file is keyed by them and only new ids are sent to the LLM.
"""

CORPUS = [
    # ------------------------------------------------------------------ English
    ('en_int_1', 'en', 'int', 'We have 3 options for you today.'),
    ('en_int_2', 'en', 'int', 'The venue can seat 250 people comfortably.'),
    ('en_int_3', 'en', 'int', 'Over 1,500 customers joined last month.'),
    ('en_int_4', 'en', 'int', 'The population is about 33,000,000 people.'),
    ('en_int_5', 'en', 'int', 'Your parcel weighs 12 kilograms and contains 40 items.'),
    ('en_int_6', 'en', 'int', 'There are 0 pending tickets in your queue.'),
    ('en_int_7', 'en', 'int', 'Room 305 is on the third floor, next to room 310.'),
    ('en_int_8', 'en', 'int', 'The code is 1000 and the backup is 2000.'),
    ('en_money_1', 'en', 'money', 'Your balance is RM1,250.50 as of today.'),
    ('en_money_2', 'en', 'money', 'The fee is RM50 per month.'),
    ('en_money_3', 'en', 'money', 'It costs RM12.05 including tax.'),
    ('en_money_4', 'en', 'money', 'The total comes to RM 3,400.'),
    ('en_money_5', 'en', 'money', 'That will be $25 or about RM110.'),
    ('en_money_6', 'en', 'money', 'You saved RM0.50 on this order.'),
    ('en_money_7', 'en', 'money', 'The house is listed at RM1.2 million.'),
    ('en_money_8', 'en', 'money', 'Minimum top-up is USD 10.'),
    ('en_money_9', 'en', 'money', 'The deposit is 500 ringgit and the rent is RM1800.'),
    ('en_decimal_1', 'en', 'decimal', 'Your temperature is 37.5 degrees.'),
    ('en_decimal_2', 'en', 'decimal', 'The average rating is 4.8 out of 5.'),
    ('en_decimal_3', 'en', 'decimal', 'Interest is charged at 3.25 per annum.'),
    ('en_decimal_4', 'en', 'decimal', 'The package is 0.75 metres long.'),
    ('en_percent_1', 'en', 'percent', 'Sales went up by 25%.'),
    ('en_percent_2', 'en', 'percent', 'Battery is at 100% and the discount is 12.5%.'),
    ('en_percent_3', 'en', 'percent', 'Only 5 % of users saw the error.'),
    ('en_phone_1', 'en', 'phone', 'Call me at 012-3456789 after lunch.'),
    ('en_phone_2', 'en', 'phone', 'Our hotline is 03-1234 5678.'),
    ('en_phone_3', 'en', 'phone', 'Reach us on +60 12-345 6789 or 1-300-88-1234.'),
    ('en_phone_4', 'en', 'phone', 'The number you dialled, 0198765432, is not in service.'),
    ('en_ic_1', 'en', 'ic', 'My IC is 960314875079.'),
    ('en_ic_2', 'en', 'ic', 'Please confirm your IC number 960314-08-5079.'),
    ('en_ic_3', 'en', 'ic', 'Passport number A12345678 was verified.'),
    ('en_date_1', 'en', 'date', 'The meeting is on 15/3/2024 at the main office.'),
    ('en_date_2', 'en', 'date', 'Your delivery is scheduled for 2024-03-15.'),
    ('en_date_3', 'en', 'date', 'The event runs from 1 March to 15 March 2024.'),
    ('en_date_4', 'en', 'date', 'Please pay before 30-06-2025.'),
    ('en_date_5', 'en', 'date', 'She was born on March 15, 1998.'),
    ('en_date_6', 'en', 'date', 'The deadline is 5 Jan 2026.'),
    ('en_date_7', 'en', 'date', 'Renewal falls on 01/12/2024.'),
    ('en_time_1', 'en', 'time', 'The meeting starts at 10:45 AM sharp.'),
    ('en_time_2', 'en', 'time', 'We close at 5pm on weekdays and 1pm on Saturdays.'),
    ('en_time_3', 'en', 'time', 'Your appointment is at 3:30 p.m. tomorrow.'),
    ('en_time_4', 'en', 'time', 'The train departs at 14:05.'),
    ('en_time_5', 'en', 'time', 'Please arrive by 9.30am.'),
    ('en_time_6', 'en', 'time', 'The office opens at 8:00 and closes at 17:00.'),
    ('en_ordinal_1', 'en', 'ordinal', "You're 3rd in the queue."),
    ('en_ordinal_2', 'en', 'ordinal', 'This is your 1st reminder and the 2nd will follow.'),
    ('en_ordinal_3', 'en', 'ordinal', 'Happy 21st birthday!'),
    ('en_ordinal_4', 'en', 'ordinal', 'Take the 12th exit on the 4th roundabout.'),
    ('en_range_1', 'en', 'range', 'We are open 9am-5pm from Monday to Friday.'),
    ('en_range_2', 'en', 'range', 'Delivery takes 3-5 working days.'),
    ('en_range_3', 'en', 'range', 'Expect a wait of 10 to 15 minutes.'),
    ('en_unit_1', 'en', 'unit', 'The bag weighs 5kg and the box is 30 cm wide.'),
    ('en_unit_2', 'en', 'unit', 'The store is 2.5 km away.'),
    ('en_unit_3', 'en', 'unit', 'It is 32°C outside today.'),
    ('en_unit_4', 'en', 'unit', 'Take 500 ml of water with 2 tablets.'),
    ('en_unit_5', 'en', 'unit', 'The plan includes 50GB of data.'),
    ('en_email_1', 'en', 'email', 'Email me at husein@site.com for details.'),
    ('en_email_2', 'en', 'email', 'Send the form to support.team@scicom.com.my today.'),
    ('en_url_1', 'en', 'url', 'Visit www.scicom.com.my to learn more.'),
    ('en_url_2', 'en', 'url', 'Go to https://example.com/help for the guide.'),
    ('en_id_1', 'en', 'id', 'Your report id is X-12340567.'),
    ('en_id_2', 'en', 'id', 'Order #4471 has been shipped.'),
    ('en_id_3', 'en', 'id', 'The reference is ABC1234 and the PIN is 0457.'),
    ('en_id_4', 'en', 'id', 'Flight MH370 was rescheduled, and your seat is 24A.'),
    ('en_id_5', 'en', 'id', 'The tracking number is 1Z999AA10123456784.'),
    ('en_year_1', 'en', 'year', 'The company was founded in 1998 and expanded in 2024.'),
    ('en_year_2', 'en', 'year', 'The policy changed in 2005.'),
    ('en_year_3', 'en', 'year', 'By 2030 we expect to double.'),
    ('en_abbr_1', 'en', 'abbr', 'Dr. Lim will call you back.'),
    ('en_abbr_2', 'en', 'abbr', 'Mr. Tan and Mrs. Lee are waiting at the lobby.'),
    ('en_abbr_3', 'en', 'abbr', 'Scicom Sdn Bhd is located on Jln Ampang.'),
    ('en_abbr_4', 'en', 'abbr', 'Bring your documents, e.g. the invoice, etc.'),
    ('en_abbr_5', 'en', 'abbr', 'Prof. Ahmad vs. the committee, approx. 20 people.'),
    ('en_acro_1', 'en', 'acro', 'Please enter the OTP sent by SMS.'),
    ('en_acro_2', 'en', 'acro', 'Bring your IC to the TNB counter in KL.'),
    ('en_acro_3', 'en', 'acro', 'The API returned an HTTP 404 error.'),
    ('en_acro_4', 'en', 'acro', 'NASA and the UN issued a joint statement.'),
    ('en_plain_1', 'en', 'plain', 'Hello there, how can I help you today?'),
    ('en_plain_2', 'en', 'plain', 'Thank you for your patience, we will get back to you shortly.'),
    ('en_plain_3', 'en', 'plain', "Don't worry, we'll sort it out."),
    ('en_plain_4', 'en', 'plain', 'She said “thank you” and left quietly.'),
    ('en_plain_5', 'en', 'plain', 'Meet me at half past three in the afternoon.'),
    ('en_mixed_1', 'en', 'mixed', 'Your total is RM1,250.50 and the meeting is at 3pm on 12/9/2026.'),
    ('en_mixed_2', 'en', 'mixed', 'Dr. Lim from Scicom Sdn Bhd will call you re: invoice no. 4471.'),
    ('en_mixed_3', 'en', 'mixed', 'Pay RM89.90 by 5/6/2025, or 10% late fee applies after 5pm.'),
    ('en_mixed_4', 'en', 'mixed', 'Order 2 units at RM199 each, delivered in 3-5 days to No. 12, Jalan Tun Razak.'),

    # ------------------------------------------------------------------ Malay
    ('ms_int_1', 'ms', 'int', 'Kami ada 3 pilihan untuk anda hari ini.'),
    ('ms_int_2', 'ms', 'int', 'Dewan ini boleh memuatkan 250 orang.'),
    ('ms_int_3', 'ms', 'int', 'Lebih 1,500 pelanggan mendaftar bulan lepas.'),
    ('ms_int_4', 'ms', 'int', 'Penduduk Malaysia kira-kira 33,000,000 orang.'),
    ('ms_int_5', 'ms', 'int', 'Tiada tiket tertunggak, jumlahnya 0.'),
    ('ms_int_6', 'ms', 'int', 'Bilik 305 di tingkat 3, sebelah bilik 310.'),
    ('ms_money_1', 'ms', 'money', 'Baki anda RM1,250.50 setakat hari ini.'),
    ('ms_money_2', 'ms', 'money', 'Yurannya RM50 sebulan.'),
    ('ms_money_3', 'ms', 'money', 'Harganya RM12.05 termasuk cukai.'),
    ('ms_money_4', 'ms', 'money', 'Jumlah keseluruhan ialah RM 3,400.'),
    ('ms_money_5', 'ms', 'money', 'Anda jimat RM0.50 untuk pesanan ini.'),
    ('ms_money_6', 'ms', 'money', 'Rumah itu berharga RM1.2 juta.'),
    ('ms_money_7', 'ms', 'money', 'Deposit 500 ringgit dan sewa RM1800 sebulan.'),
    ('ms_decimal_1', 'ms', 'decimal', 'Suhu badan anda 37.5 darjah.'),
    ('ms_decimal_2', 'ms', 'decimal', 'Penilaian purata ialah 4.8 daripada 5.'),
    ('ms_decimal_3', 'ms', 'decimal', 'Kadar faedah 3.25 setahun.'),
    ('ms_percent_1', 'ms', 'percent', 'Jualan naik 25%.'),
    ('ms_percent_2', 'ms', 'percent', 'Bateri pada 100% dan diskaun 12.5%.'),
    ('ms_phone_1', 'ms', 'phone', 'Sila hubungi 03-12345678 untuk bantuan.'),
    ('ms_phone_2', 'ms', 'phone', 'Nombor saya 012-345 6789.'),
    ('ms_phone_3', 'ms', 'phone', 'Talian kami +60 3-1234 5678 atau 1-300-88-1234.'),
    ('ms_ic_1', 'ms', 'ic', 'Nombor IC saya 960314875079.'),
    ('ms_ic_2', 'ms', 'ic', 'Sila sahkan nombor kad pengenalan 960314-08-5079.'),
    ('ms_date_1', 'ms', 'date', 'Mesyuarat pada 15/3/2024 di pejabat utama.'),
    ('ms_date_2', 'ms', 'date', 'Penghantaran dijadualkan pada 2024-03-15.'),
    ('ms_date_3', 'ms', 'date', 'Program berlangsung dari 1 Mac hingga 15 Mac 2024.'),
    ('ms_date_4', 'ms', 'date', 'Sila bayar sebelum 30-06-2025.'),
    ('ms_date_5', 'ms', 'date', 'Dia dilahirkan pada 15 Mac 1998.'),
    ('ms_date_6', 'ms', 'date', 'Tarikh akhir ialah 5 Jan 2026.'),
    ('ms_time_1', 'ms', 'time', 'Mesyuarat bermula pukul 10:45 pagi.'),
    ('ms_time_2', 'ms', 'time', 'Kami tutup pukul 5 petang pada hari bekerja.'),
    ('ms_time_3', 'ms', 'time', 'Temu janji anda pada 3:30 petang esok.'),
    ('ms_time_4', 'ms', 'time', 'Kereta api bertolak pada 14:05.'),
    ('ms_time_5', 'ms', 'time', 'Sila tiba sebelum 9.30am.'),
    ('ms_time_6', 'ms', 'time', 'Pejabat dibuka jam 8:00 dan ditutup jam 17:00.'),
    ('ms_ordinal_1', 'ms', 'ordinal', 'Anda yang ke-3 dalam barisan.'),
    ('ms_ordinal_2', 'ms', 'ordinal', 'Ini peringatan ke-1 dan yang ke-2 akan menyusul.'),
    ('ms_ordinal_3', 'ms', 'ordinal', 'Selamat hari jadi yang ke-21!'),
    ('ms_ordinal_4', 'ms', 'ordinal', 'Ambil simpang ke-12 di bulatan ke-4.'),
    ('ms_range_1', 'ms', 'range', 'Kami dibuka 9am-5pm dari Isnin hingga Jumaat.'),
    ('ms_range_2', 'ms', 'range', 'Penghantaran mengambil masa 3-5 hari bekerja.'),
    ('ms_range_3', 'ms', 'range', 'Tunggu antara 10 hingga 15 minit.'),
    ('ms_unit_1', 'ms', 'unit', 'Beg itu seberat 5kg dan kotaknya 30 cm lebar.'),
    ('ms_unit_2', 'ms', 'unit', 'Kedai itu 2.5 km dari sini.'),
    ('ms_unit_3', 'ms', 'unit', 'Suhu di luar 32°C hari ini.'),
    ('ms_unit_4', 'ms', 'unit', 'Ambil 500 ml air bersama 2 biji pil.'),
    ('ms_unit_5', 'ms', 'unit', 'Pelan ini termasuk 50GB data.'),
    ('ms_email_1', 'ms', 'email', 'Emel saya di husein@site.com untuk maklumat lanjut.'),
    ('ms_email_2', 'ms', 'email', 'Hantar borang ke support.team@scicom.com.my hari ini.'),
    ('ms_url_1', 'ms', 'url', 'Layari www.scicom.com.my untuk maklumat lanjut.'),
    ('ms_url_2', 'ms', 'url', 'Pergi ke https://example.com/bantuan untuk panduan.'),
    ('ms_id_1', 'ms', 'id', 'ID laporan anda ialah X-12340567.'),
    ('ms_id_2', 'ms', 'id', 'Pesanan #4471 telah dihantar.'),
    ('ms_id_3', 'ms', 'id', 'Rujukan ialah ABC1234 dan PIN anda 0457.'),
    ('ms_id_4', 'ms', 'id', 'Penerbangan MH370 dijadualkan semula, tempat duduk anda 24A.'),
    ('ms_year_1', 'ms', 'year', 'Syarikat ditubuhkan pada 1998 dan berkembang pada 2024.'),
    ('ms_year_2', 'ms', 'year', 'Polisi itu berubah pada tahun 2005.'),
    ('ms_year_3', 'ms', 'year', 'Menjelang 2030 kami jangka berganda.'),
    ('ms_abbr_1', 'ms', 'abbr', 'Dr. Lim akan menghubungi anda semula.'),
    ('ms_abbr_2', 'ms', 'abbr', 'En. Ahmad dan Pn. Siti sedang menunggu di lobi.'),
    ('ms_abbr_3', 'ms', 'abbr', 'Scicom Sdn Bhd terletak di Jln Ampang, KL.'),
    ('ms_abbr_4', 'ms', 'abbr', 'Bawa dokumen anda, cth. invois, dsb.'),
    ('ms_abbr_5', 'ms', 'abbr', 'Prof. Ahmad dan Dato\' Seri Azman hadir bersama Tan Sri Lim.'),
    ('ms_acro_1', 'ms', 'acro', 'Sila masukkan OTP yang dihantar melalui SMS.'),
    ('ms_acro_2', 'ms', 'acro', 'Bawa IC anda ke kaunter TNB di KL.'),
    ('ms_acro_3', 'ms', 'acro', 'Semak akaun KWSP dan LHDN anda.'),
    ('ms_plain_1', 'ms', 'plain', 'Selamat pagi, apa yang boleh saya bantu encik hari ini?'),
    ('ms_plain_2', 'ms', 'plain', 'Terima kasih kerana menghubungi kami, sila tunggu sebentar.'),
    ('ms_plain_3', 'ms', 'plain', 'Sekiranya anda mempunyai sebarang pertanyaan lanjut, jangan teragak-agak untuk menghubungi kami.'),
    ('ms_plain_4', 'ms', 'plain', 'Baiklah, saya sudah kemaskini maklumat anda di dalam sistem.'),
    ('ms_mixed_1', 'ms', 'mixed', 'Jumlah anda RM1,250.50 dan mesyuarat pada pukul 3 petang, 12/9/2026.'),
    ('ms_mixed_2', 'ms', 'mixed', 'Dr. Lim dari Scicom Sdn Bhd akan menghubungi anda berkenaan invois no. 4471.'),
    ('ms_mixed_3', 'ms', 'mixed', 'Bayar RM89.90 sebelum 5/6/2025, jika tidak denda 10% dikenakan selepas 5 petang.'),
    ('ms_mixed_4', 'ms', 'mixed', 'Pesan 2 unit pada RM199 setiap satu, dihantar dalam 3-5 hari ke No. 12, Jalan Tun Razak.'),

    # ------------------------------------------------------------------ code-switch (Malay/English)
    ('cs_1', 'cs', 'mixed', 'Okay encik, your booking is confirmed, total RM120 for 2 nights.'),
    ('cs_2', 'cs', 'mixed', 'Sorry to keep you waiting, sekejap ya, saya check order 4471 dalam system.'),
    ('cs_3', 'cs', 'mixed', 'Nanti saya call balik at 3pm ya, nombor encik 012-3456789 kan?'),
    ('cs_4', 'cs', 'mixed', 'Your bill RM85.50 dah overdue since 15/3/2024, boleh settle hari ini?'),
    ('cs_5', 'cs', 'mixed', 'Encik boleh dapat 25% discount kalau bayar before 30 June.'),
    ('cs_6', 'cs', 'plain', 'Okay lah, nanti saya check dan inform you balik ya.'),
    ('cs_7', 'cs', 'mixed', 'Nombor akaun anda ialah 1234, and your balance is RM50 today.'),
    ('cs_8', 'cs', 'mixed', 'Please pay RM120 before 5pm, kalau tidak akaun anda akan digantung selama 3 hari.'),
    ('cs_9', 'cs', 'mixed', 'Saya dah email invoice no. 4471 to you, please check by 15/3/2024.'),
    ('cs_10', 'cs', 'mixed', 'Total 3 items, harga RM45.90 semuanya, delivered in 2 days.'),
    ('cs_11', 'cs', 'mixed', 'Boleh call saya at 012-3456789 after 6pm, saya free.'),
    ('cs_12', 'cs', 'mixed', 'Discount 20% untuk pelajar, RM15 sahaja per ticket.'),
    ('cs_13', 'cs', 'mixed', 'Meeting pukul 10 pagi esok at level 12, jangan lupa bring 2 copies.'),
    ('cs_14', 'cs', 'mixed', 'Order anda dah ship, tracking number ABC1234, sampai dalam 3-5 hari.'),
    ('cs_15', 'cs', 'mixed', 'Your appointment on 5 Jun 2025 at 2.30pm, sila datang 15 minit awal.'),
    ('cs_16', 'cs', 'mixed', 'Bayaran RM250 received, thank you, resit akan dihantar dalam 24 jam.'),
    ('cs_17', 'cs', 'mixed', 'Sila tunggu, I will transfer you to extension 305 in 2 minutes.'),
    ('cs_18', 'cs', 'mixed', 'The delivery fee is RM8, tapi free kalau order lebih daripada RM100.'),

    # ------------------------------------------------------------------ Mandarin
    ('zh_int_1', 'zh', 'int', '我们今天有3个选择给您。'),
    ('zh_int_2', 'zh', 'int', '这个礼堂可以容纳250人。'),
    ('zh_int_3', 'zh', 'int', '上个月有超过1,500名客户加入。'),
    ('zh_int_4', 'zh', 'int', '马来西亚人口大约33,000,000人。'),
    ('zh_int_5', 'zh', 'int', '您的房间是305号，在3楼。'),
    ('zh_int_6', 'zh', 'int', '库存还有0件。'),
    ('zh_int_7', 'zh', 'int', '这批货有2箱，每箱200个。'),
    ('zh_money_1', 'zh', 'money', '您的余额是RM1,250.50。'),
    ('zh_money_2', 'zh', 'money', '每月费用是RM50。'),
    ('zh_money_3', 'zh', 'money', '价格是RM12.05，包括税。'),
    ('zh_money_4', 'zh', 'money', '总共是RM 3,400。'),
    ('zh_money_5', 'zh', 'money', '这间房子售价RM1.2百万。'),
    ('zh_money_6', 'zh', 'money', '押金500令吉，租金每月RM1800。'),
    ('zh_money_7', 'zh', 'money', '这个套餐是$25，大约RM110。'),
    ('zh_decimal_1', 'zh', 'decimal', '您的体温是37.5度。'),
    ('zh_decimal_2', 'zh', 'decimal', '平均评分是4.8分，满分5分。'),
    ('zh_percent_1', 'zh', 'percent', '销售额上升了25%。'),
    ('zh_percent_2', 'zh', 'percent', '电池是100%，折扣是12.5%。'),
    ('zh_phone_1', 'zh', 'phone', '请拨打03-12345678。'),
    ('zh_phone_2', 'zh', 'phone', '我的电话是012-345 6789。'),
    ('zh_phone_3', 'zh', 'phone', '热线是+60 3-1234 5678或1-300-88-1234。'),
    ('zh_ic_1', 'zh', 'ic', '我的身份证号是960314875079。'),
    ('zh_ic_2', 'zh', 'ic', '请确认您的身份证号码960314-08-5079。'),
    ('zh_date_1', 'zh', 'date', '会议在2024年3月15日举行。'),
    ('zh_date_2', 'zh', 'date', '送货日期是15/3/2024。'),
    ('zh_date_3', 'zh', 'date', '请在2025-06-30之前付款。'),
    ('zh_date_4', 'zh', 'date', '活动从3月1日到3月15日。'),
    ('zh_date_5', 'zh', 'date', '她出生于1998年3月15号。'),
    ('zh_time_1', 'zh', 'time', '会议在上午10:45开始。'),
    ('zh_time_2', 'zh', 'time', '我们下午5点关门，星期六下午1点。'),
    ('zh_time_3', 'zh', 'time', '您的预约在明天下午2点30分。'),
    ('zh_time_4', 'zh', 'time', '火车在14:05出发。'),
    ('zh_time_5', 'zh', 'time', '请在9.30am之前到达。'),
    ('zh_time_6', 'zh', 'time', '办公室8:00开门，17:00关门。'),
    ('zh_ordinal_1', 'zh', 'ordinal', '您是排队的第3位。'),
    ('zh_ordinal_2', 'zh', 'ordinal', '这是第1次提醒，第2次将会跟进。'),
    ('zh_ordinal_3', 'zh', 'ordinal', '祝您21岁生日快乐！'),
    ('zh_range_1', 'zh', 'range', '我们的营业时间是9am-5pm，星期一到星期五。'),
    ('zh_range_2', 'zh', 'range', '送货需要3-5个工作日。'),
    ('zh_range_3', 'zh', 'range', '请等待10到15分钟。'),
    ('zh_unit_1', 'zh', 'unit', '这个包5kg重，箱子30 cm宽。'),
    ('zh_unit_2', 'zh', 'unit', '商店离这里2.5 km。'),
    ('zh_unit_3', 'zh', 'unit', '今天外面32°C。'),
    ('zh_unit_4', 'zh', 'unit', '这个配套包括50GB数据。'),
    ('zh_email_1', 'zh', 'email', '请发邮件到husein@site.com。'),
    ('zh_url_1', 'zh', 'url', '请浏览www.scicom.com.my了解更多。'),
    ('zh_id_1', 'zh', 'id', '您的报告编号是X-12340567。'),
    ('zh_id_2', 'zh', 'id', '订单#4471已经发出。'),
    ('zh_id_3', 'zh', 'id', '参考号是ABC1234，密码是0457。'),
    ('zh_year_1', 'zh', 'year', '公司成立于1998年，并在2024年扩展。'),
    ('zh_year_2', 'zh', 'year', '到2030年我们预计翻倍。'),
    ('zh_abbr_1', 'zh', 'abbr', 'Dr. Lim会给您回电。'),
    ('zh_abbr_2', 'zh', 'abbr', 'Scicom Sdn Bhd位于Jln Ampang。'),
    ('zh_acro_1', 'zh', 'acro', '请输入通过SMS发送的OTP。'),
    ('zh_acro_2', 'zh', 'acro', '请带您的IC到TNB柜台。'),
    ('zh_plain_1', 'zh', 'plain', '你好，请问有什么可以帮您？'),
    ('zh_plain_2', 'zh', 'plain', '总共是一千二百五十令吉，谢谢。'),
    ('zh_plain_3', 'zh', 'plain', '我们会在两个工作日内回复您。'),
    ('zh_plain_4', 'zh', 'plain', '感谢您的耐心等待，我们会尽快处理。'),
    ('zh_mixed_1', 'zh', 'mixed', '您的总额是RM1,250.50，会议在12/9/2026下午3点。'),
    ('zh_mixed_2', 'zh', 'mixed', '请在5/6/2025之前支付RM89.90，否则下午5点后收取10%的滞纳金。'),
    ('zh_mixed_3', 'zh', 'mixed', '订购2件，每件RM199，3-5天内送到Jalan Tun Razak 12号。'),

    # ------------------------------------------------------------------ Tamil
    ('ta_int_1', 'ta', 'int', 'இன்று உங்களுக்கு 3 தேர்வுகள் உள்ளன.'),
    ('ta_int_2', 'ta', 'int', 'இந்த மண்டபத்தில் 250 பேர் அமரலாம்.'),
    ('ta_int_3', 'ta', 'int', 'கடந்த மாதம் 1,500 வாடிக்கையாளர்கள் இணைந்தனர்.'),
    ('ta_int_4', 'ta', 'int', 'மலேசியாவின் மக்கள் தொகை சுமார் 33,000,000.'),
    ('ta_int_5', 'ta', 'int', 'உங்கள் அறை 305, 3ஆம் மாடியில் உள்ளது.'),
    ('ta_int_6', 'ta', 'int', 'நிலுவையில் உள்ள டிக்கெட்டுகள் 0.'),
    ('ta_int_7', 'ta', 'int', 'எங்களிடம் 12 கிளைகள் மற்றும் 40 ஊழியர்கள் உள்ளனர்.'),
    ('ta_money_1', 'ta', 'money', 'உங்கள் இருப்பு RM1,250.50.'),
    ('ta_money_2', 'ta', 'money', 'மாதக் கட்டணம் RM50.'),
    ('ta_money_3', 'ta', 'money', 'விலை RM12.05, வரி உட்பட.'),
    ('ta_money_4', 'ta', 'money', 'மொத்தம் RM 3,400.'),
    ('ta_money_5', 'ta', 'money', 'இந்த வீட்டின் விலை RM1.2 மில்லியன்.'),
    ('ta_money_6', 'ta', 'money', 'வைப்புத்தொகை 500 ரிங்கிட், வாடகை மாதம் RM1800.'),
    ('ta_decimal_1', 'ta', 'decimal', 'உங்கள் உடல் வெப்பநிலை 37.5 டிகிரி.'),
    ('ta_decimal_2', 'ta', 'decimal', 'சராசரி மதிப்பீடு 5க்கு 4.8.'),
    ('ta_percent_1', 'ta', 'percent', 'விற்பனை 25% உயர்ந்தது.'),
    ('ta_percent_2', 'ta', 'percent', 'பேட்டரி 100%, தள்ளுபடி 12.5%.'),
    ('ta_phone_1', 'ta', 'phone', 'தயவுசெய்து 03-12345678 ஐ அழைக்கவும்.'),
    ('ta_phone_2', 'ta', 'phone', 'என் தொலைபேசி எண் 012-345 6789.'),
    ('ta_phone_3', 'ta', 'phone', 'எங்கள் ஹாட்லைன் +60 3-1234 5678 அல்லது 1-300-88-1234.'),
    ('ta_ic_1', 'ta', 'ic', 'என் அடையாள அட்டை எண் 960314875079.'),
    ('ta_ic_2', 'ta', 'ic', 'உங்கள் அடையாள அட்டை எண் 960314-08-5079 ஐ உறுதிப்படுத்துங்கள்.'),
    ('ta_date_1', 'ta', 'date', 'கூட்டம் 15/3/2024 அன்று நடைபெறும்.'),
    ('ta_date_2', 'ta', 'date', 'டெலிவரி 2024-03-15 அன்று திட்டமிடப்பட்டுள்ளது.'),
    ('ta_date_3', 'ta', 'date', 'நிகழ்ச்சி மார்ச் 1 முதல் மார்ச் 15, 2024 வரை.'),
    ('ta_date_4', 'ta', 'date', '30-06-2025 க்கு முன் பணம் செலுத்துங்கள்.'),
    ('ta_date_5', 'ta', 'date', 'அவர் 15 மார்ச் 1998 இல் பிறந்தார்.'),
    ('ta_time_1', 'ta', 'time', 'கூட்டம் காலை 10:45 மணிக்கு தொடங்கும்.'),
    ('ta_time_2', 'ta', 'time', 'நாங்கள் மாலை 5pm மணிக்கு மூடுகிறோம்.'),
    ('ta_time_3', 'ta', 'time', 'உங்கள் சந்திப்பு நாளை 3:30 p.m. மணிக்கு.'),
    ('ta_time_4', 'ta', 'time', 'ரயில் 14:05 மணிக்கு புறப்படும்.'),
    ('ta_time_5', 'ta', 'time', 'அலுவலகம் 8:00 மணிக்கு திறந்து 17:00 மணிக்கு மூடும்.'),
    ('ta_ordinal_1', 'ta', 'ordinal', 'நீங்கள் வரிசையில் 3வது.'),
    ('ta_ordinal_2', 'ta', 'ordinal', 'இது 1ஆவது நினைவூட்டல், 2ஆவது பின்தொடரும்.'),
    ('ta_ordinal_3', 'ta', 'ordinal', '21ஆம் பிறந்தநாள் வாழ்த்துக்கள்!'),
    ('ta_range_1', 'ta', 'range', 'நாங்கள் திங்கள் முதல் வெள்ளி வரை 9am-5pm திறந்திருக்கிறோம்.'),
    ('ta_range_2', 'ta', 'range', 'டெலிவரிக்கு 3-5 வேலை நாட்கள் ஆகும்.'),
    ('ta_range_3', 'ta', 'range', '10 முதல் 15 நிமிடங்கள் காத்திருக்கவும்.'),
    ('ta_unit_1', 'ta', 'unit', 'பை 5kg எடை, பெட்டி 30 cm அகலம்.'),
    ('ta_unit_2', 'ta', 'unit', 'கடை இங்கிருந்து 2.5 km தொலைவில் உள்ளது.'),
    ('ta_unit_3', 'ta', 'unit', 'இன்று வெளியே 32°C.'),
    ('ta_unit_4', 'ta', 'unit', 'இந்த திட்டத்தில் 50GB டேட்டா அடங்கும்.'),
    ('ta_email_1', 'ta', 'email', 'விவரங்களுக்கு husein@site.com க்கு மின்னஞ்சல் அனுப்புங்கள்.'),
    ('ta_url_1', 'ta', 'url', 'மேலும் அறிய www.scicom.com.my ஐ பார்வையிடுங்கள்.'),
    ('ta_id_1', 'ta', 'id', 'உங்கள் அறிக்கை எண் X-12340567.'),
    ('ta_id_2', 'ta', 'id', 'ஆர்டர் #4471 அனுப்பப்பட்டது.'),
    ('ta_id_3', 'ta', 'id', 'குறிப்பு ABC1234, PIN 0457.'),
    ('ta_year_1', 'ta', 'year', 'நிறுவனம் 1998 இல் நிறுவப்பட்டு 2024 இல் விரிவடைந்தது.'),
    ('ta_year_2', 'ta', 'year', '2030 க்குள் இரட்டிப்பாகும் என எதிர்பார்க்கிறோம்.'),
    ('ta_abbr_1', 'ta', 'abbr', 'Dr. Lim உங்களை மீண்டும் அழைப்பார்.'),
    ('ta_abbr_2', 'ta', 'abbr', 'Scicom Sdn Bhd Jln Ampang இல் அமைந்துள்ளது.'),
    ('ta_acro_1', 'ta', 'acro', 'SMS மூலம் அனுப்பப்பட்ட OTP ஐ உள்ளிடுங்கள்.'),
    ('ta_acro_2', 'ta', 'acro', 'உங்கள் IC ஐ TNB கவுண்டருக்கு கொண்டு வாருங்கள்.'),
    ('ta_plain_1', 'ta', 'plain', 'வணக்கம், நான் உங்களுக்கு எப்படி உதவ முடியும்?'),
    ('ta_plain_2', 'ta', 'plain', 'உங்கள் பொறுமைக்கு நன்றி, விரைவில் பதிலளிக்கிறோம்.'),
    ('ta_plain_3', 'ta', 'plain', 'மொத்தம் ஆயிரத்து இருநூற்று ஐம்பது ரிங்கிட், நன்றி.'),
    ('ta_plain_4', 'ta', 'plain', 'நாங்கள் இரண்டு வேலை நாட்களுக்குள் பதிலளிப்போம்.'),
    ('ta_mixed_1', 'ta', 'mixed', 'உங்கள் மொத்தம் RM1,250.50, கூட்டம் 12/9/2026 அன்று 3pm மணிக்கு.'),
    ('ta_mixed_2', 'ta', 'mixed', '5/6/2025 க்கு முன் RM89.90 செலுத்துங்கள், இல்லையெனில் 10% தாமதக் கட்டணம்.'),
    ('ta_mixed_3', 'ta', 'mixed', '2 யூனிட்கள், ஒவ்வொன்றும் RM199, 3-5 நாட்களில் Jalan Tun Razak, No. 12 க்கு.'),
]

BY_ID = {c[0]: c for c in CORPUS}
